REL_FILES = Holmakefile CCSScript.sml *Lib.sig *Lib.sml *Conv.sig *Conv.sml tokens.tex \
	CCSSyntax.sml CCSSyntax.sig selftest.sml \
	StrongEQScript.sml StrongLawsScript.sml \
	WeakEQScript.sml WeakLawsScript.sml \
	ObsCongrScript.sml ObsCongrLawsScript.sml \
	CoarsestCongrScript.sml ExampleScript.sml \
	CongruenceScript.sml TraceScript.sml \
	ExpansionScript.sml ContractionScript.sml \
	BisimulationUptoScript.sml UniqueSolutionsScript.sml \
        MultivariateScript.sml

all:
	Holmake

clean:
	Holmake clean
	@rm -rf .HOLMK .hollogs

.PHONY: all
